language: node_js
node_js:
  - "8.5"
os: osx

branches:
  only:
    - master
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- apt-get install xvfb
- sh -e /etc/init.d/xvfb start
services:
  mongodb

before_script:
- cd smart-note 
# - npm cache clean --force
# - npm install -g @angular/cli
# - npm install -g karma
# - npm install

script:
  # sh build.sh

notifications:
  email:
    on_failure: change
    on_success: change
