language: node_js
node_js:
  - "8.5"
os: osx

branches:
  only:
    - master
before_install:
 - export CHROME_BIN=chromium-browser

services:
  mongodb

before_script:
- npm install -g @angular/cli
- npm install -g karma
- npm install
- cd smart-note 
- ng build

script:
  # sh build.sh

notifications:
  email:
    on_failure: change
    on_success: change
