language: node_js
node_js:
  - "8.5"
os: osx

branches:
  only:
    - master

before_script:
  

script:
  sh build.sh

serives:
  mongodb


notifications:
  email:
    on_failure: change
    on_success: change